language: python

python: "2.7"

install: pip install -r requirements.txt --use-mirrors

before_script:
- wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.8.zip -nv
- unzip -q google_appengine_1.9.8.zip

script: tests/testrunner.py